# Keejob bronze exploration

In [64]:
import json
from pathlib import Path

import pandas as pd
from bs4 import BeautifulSoup

In [65]:
#saving bronze paths in a variable "records"



REPORT_PATH = Path(
    "data/reports/keejob/bfce5dcc9bf046eaaa8aff9070e0a269.json"
)

with REPORT_PATH.open(encoding="utf-8") as file:
    report = json.load(file)

records = []
df = pd.json_normalize(records, sep=".")

print("Rows and columns:", df.shape)
df.head()
for saved in report["saved_records"]:
    with Path(saved["bronze_path"]).open(encoding="utf-8") as file:
        records.append(json.load(file))

print(f"Loaded {len(records)} observations")

Rows and columns: (0, 0)
Loaded 683 observations

In [66]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [67]:
df = pd.json_normalize(records, sep=".")

print("Rows and columns:", df.shape)
df.head()

Rows and columns: (683, 36)

,metadata.source,metadata.requested_url,metadata.response_url,metadata.collected_at,metadata.http_status,metadata.content_type,payload.@context,payload.@type,payload.title,payload.description,payload.identifier.@type,payload.identifier.name,payload.identifier.value,payload.url,payload.employmentType,payload.directApply,payload.datePosted,payload.validThrough,payload.hiringOrganization.@type,payload.hiringOrganization.name,payload.hiringOrganization.sameAs,payload.hiringOrganization.logo,payload.jobLocation.@type,payload.jobLocation.address.@type,payload.jobLocation.address.addressLocality,payload.jobLocation.address.addressRegion,payload.jobLocation.address.addressCountry,payload.baseSalary.@type,payload.baseSalary.currency,payload.baseSalary.value.@type,payload.baseSalary.value.minValue,payload.baseSalary.value.maxValue,payload.baseSalary.value.unitText,payload.jobLocationType,payload.applicantLocationRequirements.@type,payload.applicantLocationRequirements.name
0,keejob,https://www.keejob.com/offres-emploi/103174/co...,https://www.keejob.com/offres-emploi/103174/co...,2026-10-17T10:06:03.746846+00:00,200,text/html; charset=utf-8,https://schema.org/,JobPosting,Un Comptable,<p></p><p>SCET-TUNISIE intervient en Tunisie a...,PropertyValue,Keejob,103174,https://www.keejob.com/offres-emploi/103174/co...,FULL_TIME,True,2026-10-10,2026-10-24T23:59:59,Organization,SCET TUNISIE,https://www.keejob.com/offres-emploi/entrepris...,https://www.keejob.com/media/recruiter/recruit...,Place,PostalAddress,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,keejob,https://www.keejob.com/offres-emploi/132555/ge...,https://www.keejob.com/offres-emploi/132555/ge...,2026-10-17T10:06:06.167847+00:00,200,text/html; charset=utf-8,https://schema.org/,JobPosting,Gestionnaire,<p>Société de renommée cherche à recruter un g...,PropertyValue,Keejob,132555,https://www.keejob.com/offres-emploi/132555/ge...,OTHER,True,2026-10-06,2026-11-05T23:59:59,Organization,Entreprise Anonyme,NaN,NaN,Place,PostalAddress,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,keejob,https://www.keejob.com/offres-emploi/206430/di...,https://www.keejob.com/offres-emploi/206430/di...,2026-10-17T10:06:08.492179+00:00,200,text/html; charset=utf-8,https://schema.org/,JobPosting,DIRECTEUR D'USINE,<p>SOCIÉTÉ OPÉRANT DANS LE SECTEUR INDUSTRIEL ...,PropertyValue,Keejob,206430,https://www.keejob.com/offres-emploi/206430/di...,OTHER,True,2026-10-14,2026-11-13T23:59:59,Organization,Entreprise Anonyme,NaN,NaN,Place,PostalAddress,Zaghouan,Zaghouan,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,keejob,https://www.keejob.com/offres-emploi/212195/te...,https://www.keejob.com/offres-emploi/212195/te...,2026-10-17T10:06:10.794576+00:00,200,text/html; charset=utf-8,https://schema.org/,JobPosting,Technicien Ascenseur,<p>&nbsp;</p><p>L'entreprise Tunisienne des As...,PropertyValue,Keejob,212195,https://www.keejob.com/offres-emploi/212195/te...,OTHER,True,2026-10-02,2026-11-01T23:59:59,Organization,ENTREPRISE TUNISIENNE DES ASCENSEURS,https://www.keejob.com/offres-emploi/entrepris...,NaN,Place,PostalAddress,Ariana,Ariana,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,keejob,https://www.keejob.com/offres-emploi/224590/4-...,https://www.keejob.com/offres-emploi/224590/4-...,2026-10-17T10:06:13.115472+00:00,200,text/html; charset=utf-8,https://schema.org/,JobPosting,Techniciens Réseau et Maintenance,<p>I2S cherche à recruter 2 Techniciens en Rés...,PropertyValue,Keejob,224590,https://www.keejob.com/offres-emploi/224590/4-...,OTHER,True,2026-10-09,2026-11-08T23:59:59,Organization,C AND A TRADIGI SERVICES,https://www.keejob.com/offres-emploi/entrepris...,NaN,Place,PostalAddress,Centre ville,Tunis,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df.drop(columns=["payload.@type","payload.identifier.@type","payload.hiringOrganization.@type","payload.jobLocation.@type","payload.jobLocation.address.@type","payload.baseSalary.@type","payload.baseSalary.value.@type","payload.applicantLocationRequirements.@type"],inplace=True)

df.drop(columns=["payload.hiringOrganization.logo"],inplace=True)
df.drop(columns=["payload.applicantLocationRequirements.name"],inplace=True)

df.drop(columns=["metadata.requested_url","metadata.response_url","metadata.http_status","metadata.content_type","payload.@context"],inplace=True)

In [69]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
metadata.source,683,1,keejob,683,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metadata.collected_at,683,683,2026-10-17T10:06:03.746846+00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.title,683,643,Comptable,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.description,683,658,"<p><p>Pour Accompagner son développement, le g...",6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.identifier.name,683,1,Keejob,683,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.identifier.value,683,683,103174,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.url,683,683,https://www.keejob.com/offres-emploi/103174/co...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.employmentType,683,6,FULL_TIME,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.directApply,683,2,True,674,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.datePosted,683,28,2026-10-17,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.validThrough,683,30,2026-10-17T23:59:59,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.hiringOrganization.name,683,253,Entreprise Anonyme,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.hiringOrganization.sameAs,567,252,https://www.keejob.com/offres-emploi/entrepris...,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.jobLocation.address.addressLocality,637,92,Tunis,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.jobLocation.address.addressRegion,635,22,Tunis,221,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.jobLocation.address.addressCountry,683,3,TN,679,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.baseSalary.currency,149,1,TND,149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.baseSalary.value.minValue,149.0,NaN,NaN,NaN,1307.617477,1464.06104,467.0,800.0,1000.0,1400.0,9998.0
payload.baseSalary.value.maxValue,149.0,NaN,NaN,NaN,2615.993081,8246.201586,501.0,1000.0,1500.0,2000.0,99998.0
payload.baseSalary.value.unitText,149,1,MONTH,149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payload.jobLocationType,2,1,TELECOMMUTE,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
# df[df["payload.baseSalary.value.maxValue"]< df["payload.baseSalary.value.minValue"]]

In [71]:
# df[df["payload.baseSalary.value.minValue"]<0]

In [72]:
# df["payload.jobLocation.address.addressCountry"]!="TN"

In [73]:
df.drop(df[df["payload.jobLocation.address.addressCountry"]!="TN"].index,inplace=True)

In [74]:
date_formats = {
    "payload.datePosted": "%Y-%m-%d",
    "payload.validThrough": "%Y-%m-%dT%H:%M:%S",
}

for column, date_format in date_formats.items():
    df[column] = pd.to_datetime(
        df[column],
        format=date_format,
        errors="raise",
    )

df["metadata.collected_at"] = pd.to_datetime(
    df["metadata.collected_at"],
    utc=True,
    errors="raise",
)

invalid_dates = df.loc[
    df["payload.validThrough"] < df["payload.datePosted"],
    [
        "payload.identifier.value",
        "payload.title",
        "payload.datePosted",
        "payload.validThrough",
    ],
]

print("Expiry earlier than publication:", len(invalid_dates))
display(invalid_dates)

Expiry earlier than publication: 0

Empty DataFrame
Columns: [payload.identifier.value, payload.title, payload.datePosted, payload.validThrough]
Index: []

In [75]:
df.head()

,metadata.source,metadata.collected_at,payload.title,payload.description,payload.identifier.name,payload.identifier.value,payload.url,payload.employmentType,payload.directApply,payload.datePosted,payload.validThrough,payload.hiringOrganization.name,payload.hiringOrganization.sameAs,payload.jobLocation.address.addressLocality,payload.jobLocation.address.addressRegion,payload.jobLocation.address.addressCountry,payload.baseSalary.currency,payload.baseSalary.value.minValue,payload.baseSalary.value.maxValue,payload.baseSalary.value.unitText,payload.jobLocationType
0,keejob,2026-10-17 10:06:03.746846+00:00,Un Comptable,<p></p><p>SCET-TUNISIE intervient en Tunisie a...,Keejob,103174,https://www.keejob.com/offres-emploi/103174/co...,FULL_TIME,True,2026-10-10,2026-10-24 23:59:59,SCET TUNISIE,https://www.keejob.com/offres-emploi/entrepris...,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN
1,keejob,2026-10-17 10:06:06.167847+00:00,Gestionnaire,<p>Société de renommée cherche à recruter un g...,Keejob,132555,https://www.keejob.com/offres-emploi/132555/ge...,OTHER,True,2026-10-06,2026-11-05 23:59:59,Entreprise Anonyme,NaN,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN
2,keejob,2026-10-17 10:06:08.492179+00:00,DIRECTEUR D'USINE,<p>SOCIÉTÉ OPÉRANT DANS LE SECTEUR INDUSTRIEL ...,Keejob,206430,https://www.keejob.com/offres-emploi/206430/di...,OTHER,True,2026-10-14,2026-11-13 23:59:59,Entreprise Anonyme,NaN,Zaghouan,Zaghouan,TN,NaN,NaN,NaN,NaN,NaN
3,keejob,2026-10-17 10:06:10.794576+00:00,Technicien Ascenseur,<p>&nbsp;</p><p>L'entreprise Tunisienne des As...,Keejob,212195,https://www.keejob.com/offres-emploi/212195/te...,OTHER,True,2026-10-02,2026-11-01 23:59:59,ENTREPRISE TUNISIENNE DES ASCENSEURS,https://www.keejob.com/offres-emploi/entrepris...,Ariana,Ariana,TN,NaN,NaN,NaN,NaN,NaN
4,keejob,2026-10-17 10:06:13.115472+00:00,Techniciens Réseau et Maintenance,<p>I2S cherche à recruter 2 Techniciens en Rés...,Keejob,224590,https://www.keejob.com/offres-emploi/224590/4-...,OTHER,True,2026-10-09,2026-11-08 23:59:59,C AND A TRADIGI SERVICES,https://www.keejob.com/offres-emploi/entrepris...,Centre ville,Tunis,TN,NaN,NaN,NaN,NaN,NaN

In [76]:
from bs4 import BeautifulSoup


def extract_description_text(html):
    if pd.isna(html):
        return pd.NA

    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style"]):
        tag.decompose()

    text = soup.get_text(separator=" ", strip=True)

    return " ".join(text.split())


df["payload.description"] = df["payload.description"].map(
    extract_description_text
)

In [77]:
df.head()

,metadata.source,metadata.collected_at,payload.title,payload.description,payload.identifier.name,payload.identifier.value,payload.url,payload.employmentType,payload.directApply,payload.datePosted,payload.validThrough,payload.hiringOrganization.name,payload.hiringOrganization.sameAs,payload.jobLocation.address.addressLocality,payload.jobLocation.address.addressRegion,payload.jobLocation.address.addressCountry,payload.baseSalary.currency,payload.baseSalary.value.minValue,payload.baseSalary.value.maxValue,payload.baseSalary.value.unitText,payload.jobLocationType
0,keejob,2026-10-17 10:06:03.746846+00:00,Un Comptable,SCET-TUNISIE intervient en Tunisie ainsi qu’à ...,Keejob,103174,https://www.keejob.com/offres-emploi/103174/co...,FULL_TIME,True,2026-10-10,2026-10-24 23:59:59,SCET TUNISIE,https://www.keejob.com/offres-emploi/entrepris...,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN
1,keejob,2026-10-17 10:06:06.167847+00:00,Gestionnaire,Société de renommée cherche à recruter un gest...,Keejob,132555,https://www.keejob.com/offres-emploi/132555/ge...,OTHER,True,2026-10-06,2026-11-05 23:59:59,Entreprise Anonyme,NaN,El Menzah,Tunis,TN,NaN,NaN,NaN,NaN,NaN
2,keejob,2026-10-17 10:06:08.492179+00:00,DIRECTEUR D'USINE,SOCIÉTÉ OPÉRANT DANS LE SECTEUR INDUSTRIEL REC...,Keejob,206430,https://www.keejob.com/offres-emploi/206430/di...,OTHER,True,2026-10-14,2026-11-13 23:59:59,Entreprise Anonyme,NaN,Zaghouan,Zaghouan,TN,NaN,NaN,NaN,NaN,NaN
3,keejob,2026-10-17 10:06:10.794576+00:00,Technicien Ascenseur,L'entreprise Tunisienne des Ascenseurs est à l...,Keejob,212195,https://www.keejob.com/offres-emploi/212195/te...,OTHER,True,2026-10-02,2026-11-01 23:59:59,ENTREPRISE TUNISIENNE DES ASCENSEURS,https://www.keejob.com/offres-emploi/entrepris...,Ariana,Ariana,TN,NaN,NaN,NaN,NaN,NaN
4,keejob,2026-10-17 10:06:13.115472+00:00,Techniciens Réseau et Maintenance,I2S cherche à recruter 2 Techniciens en Réseau...,Keejob,224590,https://www.keejob.com/offres-emploi/224590/4-...,OTHER,True,2026-10-09,2026-11-08 23:59:59,C AND A TRADIGI SERVICES,https://www.keejob.com/offres-emploi/entrepris...,Centre ville,Tunis,TN,NaN,NaN,NaN,NaN,NaN